---
- hosts: localhost

  tasks:
    - include_role:
        name: install_homebrew

    - name: Install homebrew packages
      community.general.homebrew:
        name:
          - chezmoi
          - dotnet
          - fzf
          - jaq
          - macvim
          - mas
          - pipenv
          - schappim/ocr/ocr
          - starship
          - zoxide
        state: present
        update_homebrew: true

    - name: Install homebrew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      with_items:
        - brave-browser
        - docker
        - gpg-suite
        - iterm2
        - intellij-idea
        - keepingyouawake
        - keka
        - rider
        - skype
        - sourcetree
        - spotify
        - viscosity
        - visual-studio-code
        - vlc

    - name: Install apps from App Store
      ansible.builtin.shell: mas install {{ item }}
      with_items:
        - 1440147259 # AdGuard for Safari
        - 1544743900 # Hush Nag Blocker
        - 1276493162 # reMarkable desktop
        - 803453959  # Slack
        - 310633997  # WhatsApp
        - 497799835  # Xcode

    - include_role:
        name: download_and_install_font
      vars:
        font_url: "{{ item }}"
      loop:
        - https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip
        - https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip

    - include_role:
        name: install_ohmyzsh

    - name: Install SDKMAN
      ansible.builtin.shell: bash -c "$(curl -s https://get.sdkman.io)"

    - name: Install Vundle for vim
      ansible.builtin.git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: "/Users/{{ lookup('env', 'USER') }}/.vim/bundle/Vundle.vim"

    - name: Add Visual Studio Code extensions
      ansible.builtin.shell: "{{ homebrew_bin_path }}/code --install-extension {{ item }}"
      with_items:
        - streetsidesoftware.code-spell-checker # Code Spell Checker
        - eamodio.gitlens                       # GitLens - Git supercharged
        - esbenp.prettier-vscode                # Prettier - Code formtter
        - ms-python.python                      # Python
        - fabiospampinato.vscode-todo-plus      # Todo+

    - name: Create Visual Studio Code configuration
      ansible.builtin.template:
        src: templates/vscode_settings.json.j2
        dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/settings.json
        owner: "{{ lookup('env', 'USER') }}"
        force: yes

    - name: Configure dotfiles
      block:
        - name: Initialize chezmoi
          ansible.builtin.shell: "{{ homebrew_bin_path }}/chezmoi init https://github.com/josefeg/dotfiles.git"

        - name: Install dotfiles
          ansible.builtin.shell: "{{ homebrew_bin_path }}/chezmoi apply --force"
...
